#!/bin/zsh
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT="$ROOT/firmware/src/fonts/jetbrains_mono_ascii_8.h"
TMP_DIR="$(mktemp -d /tmp/opencode-buddy-font.XXXXXX)"
trap 'find "$TMP_DIR" -type f -delete; find "$TMP_DIR" -depth -type d -exec rmdir {} +' EXIT

FONT_URL="https://raw.githubusercontent.com/JetBrains/JetBrainsMono/v2.304/fonts/ttf/JetBrainsMono-Regular.ttf"
FONT_SHA256="a0bf60ef0f83c5ed4d7a75d45838548b1f6873372dfac88f71804491898d138f"
BOLD_FONT_URL="https://raw.githubusercontent.com/JetBrains/JetBrainsMono/v2.304/fonts/ttf/JetBrainsMono-Bold.ttf"
BOLD_FONT_SHA256="5590990c82e097397517f275f430af4546e1c45cff408bde4255dad142479dcb"
ADAFRUIT_COMMIT="ac6d7c3869a693d406f77b9bfcd486b0673169f0"
CONVERTER_URL="https://raw.githubusercontent.com/adafruit/Adafruit-GFX-Library/$ADAFRUIT_COMMIT/fontconvert/fontconvert.c"
CONVERTER_SHA256="42e70906d68e4a7bced1c47a7bb12d2a86c29484eeb564f76449ea7a9b6c3ba1"
GFXFONT_URL="https://raw.githubusercontent.com/adafruit/Adafruit-GFX-Library/$ADAFRUIT_COMMIT/gfxfont.h"
GFXFONT_SHA256="4e1b06371217d63102bac242d4a3ec8dcaff93cd34b4241bbc39eda521a1be11"
CURL=(curl --retry 3 --retry-all-errors -fsSL)

"${CURL[@]}" "$FONT_URL" -o "$TMP_DIR/JetBrainsMono-Regular.ttf"
"${CURL[@]}" "$BOLD_FONT_URL" -o "$TMP_DIR/JetBrainsMono-Bold.ttf"
mkdir -p "$TMP_DIR/fontconvert"
"${CURL[@]}" "$CONVERTER_URL" -o "$TMP_DIR/fontconvert/fontconvert.c"
"${CURL[@]}" "$GFXFONT_URL" -o "$TMP_DIR/gfxfont.h"

verify_sha256() {
  local expected="$1"
  local file_path="$2"
  local actual="$(shasum -a 256 "$file_path" | awk '{print $1}')"
  if [[ "$actual" != "$expected" ]]; then
    print -u2 "SHA-256 mismatch for $file_path: expected $expected, got $actual"
    exit 1
  fi
}

verify_sha256 "$FONT_SHA256" "$TMP_DIR/JetBrainsMono-Regular.ttf"
verify_sha256 "$BOLD_FONT_SHA256" "$TMP_DIR/JetBrainsMono-Bold.ttf"
verify_sha256 "$CONVERTER_SHA256" "$TMP_DIR/fontconvert/fontconvert.c"
verify_sha256 "$GFXFONT_SHA256" "$TMP_DIR/gfxfont.h"

# Adafruit fontconvert renders the default cmap glyph and has no OpenType
# feature switch. Bake JetBrains Mono's `zero` feature into U+0030 by loading
# its named alternate while leaving every other character on the normal cmap.
perl -0pi -e 's/if \(\(err = FT_Load_Char\(face, i, FT_LOAD_TARGET_MONO\)\)\) \{/FT_UInt glyph_index = FT_Get_Char_Index(face, i);\n    if (i == '\''0'\'') {\n      glyph_index = FT_Get_Name_Index(face, "zero.zero");\n      if (!glyph_index) {\n        fprintf(stderr, "Font has no zero.zero glyph\\n");\n        return 1;\n      }\n    }\n    if ((err = FT_Load_Glyph(face, glyph_index, FT_LOAD_TARGET_MONO))) {/g' \
  "$TMP_DIR/fontconvert/fontconvert.c"
if ! grep -q 'FT_Get_Name_Index(face, "zero.zero")' \
  "$TMP_DIR/fontconvert/fontconvert.c"; then
  print -u2 "Unable to enable JetBrains Mono slashed zero"
  exit 1
fi

cc "$TMP_DIR/fontconvert/fontconvert.c" $(pkg-config --cflags --libs freetype2) \
  -o "$TMP_DIR/fontconvert-bin"
"$TMP_DIR/fontconvert-bin" "$TMP_DIR/JetBrainsMono-Regular.ttf" 8 32 126 \
  > "$TMP_DIR/regular-8.h"
"$TMP_DIR/fontconvert-bin" "$TMP_DIR/JetBrainsMono-Regular.ttf" 7 32 126 \
  > "$TMP_DIR/regular-7.h"
"$TMP_DIR/fontconvert-bin" "$TMP_DIR/JetBrainsMono-Regular.ttf" 14 45 58 \
  > "$TMP_DIR/regular-14-numbers.h"
"$TMP_DIR/fontconvert-bin" "$TMP_DIR/JetBrainsMono-Regular.ttf" 20 45 58 \
  > "$TMP_DIR/regular-20-numbers.h"
"$TMP_DIR/fontconvert-bin" "$TMP_DIR/JetBrainsMono-Bold.ttf" 6 32 126 \
  > "$TMP_DIR/bold-6.h"

mkdir -p "${OUTPUT:h}"
{
  print '#pragma once'
  print ''
  print '#include <M5Unified.h>'
  print ''
  print '// JetBrains Mono Regular and Bold v2.304 dashboard subsets.'
  print '// Regular 7/8 pt include ASCII U+0020-U+007E.'
  print '// Regular 14/20 pt include U+002D-U+003A for clock digits.'
  print '// The OpenType slashed-zero alternate is baked into U+0030.'
  print '// Generated by scripts/generate-jetbrains-mono-font.sh.'
  print '// Licensed under firmware/licenses/JetBrainsMono-OFL.txt.'
  print 'namespace opencode_buddy_fonts {'
  sed \
    -e 's/^const uint8_t /static const uint8_t /' \
    -e 's/^const GFXglyph /static const lgfx::GFXglyph /' \
    -e 's/^const GFXfont /static const lgfx::GFXfont /' \
    -e 's/(GFXglyph \*)/(lgfx::GFXglyph *)/' \
    "$TMP_DIR/regular-8.h" \
    "$TMP_DIR/regular-7.h" \
    "$TMP_DIR/regular-14-numbers.h" \
    "$TMP_DIR/regular-20-numbers.h" \
    "$TMP_DIR/bold-6.h"
  print '}  // namespace opencode_buddy_fonts'
} > "$OUTPUT.tmp"
mv "$OUTPUT.tmp" "$OUTPUT"

echo "$OUTPUT"
